#!/bin/bash
DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

# Colors Variables
red="1"
green="2"
yellow="3"
blue="4"
purple="5"
lightblue="6"
grey="7"

textColor=$(tput setaf $lightblue)
normal=$(tput sgr0)

# While loops for script arguments
while [ $# -gt 0 ]
do
	case "$1" in

    -c|--color)
			GR='\033[00;32m'
			YE='\033[00;33m'
			LR='\033[01;31m'
			RE='\033[00;31m'
			PU='\033[00;35m'
			CY='\033[00;36m'
			BL='\033[00;34m'
    	    shift
            ;;
	-red)
			textColor=$(tput setaf $red)
			shift
			;;
	-green)
			textColor=$(tput setaf $green)
			shift
			;;
	-yellow)
			textColor=$(tput setaf $yellow)
			shift
			;;
	-blue)
			textColor=$(tput setaf $blue)
			shift
			;;
	-purple)
			textColor=$(tput setaf $purple)
			shift
			;;
	-grey)
			textColor=$(tput setaf $grey)
			shift
			;;
	*)
			break
			;;
	esac
done

# ==USER==
user=$(whoami)

# ==HOSTNAME==
hostname=$(HOSTNAME | sed 's/.local//g' | sed 's/.gateway//g' )
# if hostname is >35 characters, truncates to make it fit on std. 80 window
if [ ${#HOSTNAME} -gt 35 ]
then
   hostname=${HOSTNAME:0:35}
fi

# ==MODEL==
serial_number=$(ioreg -c IOPlatformExpertDevice -d 2 | awk -F\" '/IOPlatformSerialNumber/{print $(NF-1)}')

if [[ $serial_number =~ ^VM ]]; then
	modelname="Virtual Machine"
else
	modelname=$( curl -s http://support-sp.apple.com/sp/product?cc=$( ioreg -c IOPlatformExpertDevice -d 2 | awk -F\" '/IOPlatformSerialNumber/{ sn=$(NF-1); if (length(sn) == 12) count=3; else if (length(sn) == 11) count=2; print substr(sn, length(sn) - count, length(sn))}' ) | xmllint --xpath '//configCode/text()' - )
fi

model=$(sysctl -n hw.model)
modelname="$modelname ($model)"

# ==GRAPHICS==
graphics=$(system_profiler SPDisplaysDataType |
awk '/Model/{for (i=1; i<=NF-2; i++) $i = $(i+2); NF-=2; print}' | paste -sd "/" -)

graphicsnoBrand=$(system_profiler SPDisplaysDataType |
awk '/Model/{for (i=1; i<=NF-3; i++) $i = $(i+3); NF-=3; print}' | paste -sd "/" -)

resolution=$(system_profiler SPDisplaysDataType | grep Resolution | cut -d':' -f2 | sed -e 's/^[ \t]*//' | awk '$1=$1' ORS=' ')

# Use system_profiler to find graphics cards, then awk to find 'Model'
# Output of this step is lines such as this:
# > Chipset Model: Intel HD Graphics
# > Chipset Model: NVIDIA GeForce GT 330M
# Use awk with a loop to print the arguments after Model: to end of line
# Use paste to join multiple lines together with a slash if necessary.
# Sample output:
# > graphics:        Intel HD Graphics/NVIDIA GeForce GT 330M
# > graphicsnoBrand: HD Graphics/GeForce GT 330M

# ==IP ADDRESS==
# Find an active network interface
interface=$(route get 0.0.0.0 2>/dev/null | awk '/interface: / {print $2}')

# Obtain the computer's IP address.
ip_address=$(ipconfig getifaddr ${interface})


# ==VERSION==
product_version=$(sw_vers -productVersion)
product_build=$(sw_vers -buildVersion)

os_marketing_name=$(curl -s "http://support-sp.apple.com/sp/product?edid=$(sw_vers -productVersion)&lang=en-US_US" |\
	xmllint --xpath '//configCode/text()' -)

version="$os_marketing_name $product_version ($product_build)"

# ==UPTIME==
if [ "$(uptime | sed -e "s/:/ /2" | sed -e "s/,/ /2" | awk '{print $6}')" = "users" ]
    then
        # 1 hour < uptime < 1 day
        uptime="$(uptime | sed -e "s/:/ /2" | sed -e "s/,/ /2" | awk '{$4=substr($4,1,length($4)-1); print $3 " hours and " $4 " minutes"}')"
    else
        if [ "$(uptime | sed -e "s/:/ /2" | sed -e "s/,/ /2" | awk '{print $5}')" = "min," ]
            then
                # uptime < 1 hour
                uptime="$(uptime | sed -e "s/:/ /2" | sed -e "s/:/ /2" | sed -e "s/,/ /2" | awk '{print $4 " minutes"}')"
            else
            # uptime > 1 day
            uptime="$(uptime | sed -e "s/:/ /2" | sed -e "s/,/ /2" | awk '{print $3 " days, " $5 " hours and " $6 " minutes"}')"
        fi
fi

# ==SHELL==
shell="$SHELL"

# ==TERMINAL==
terminal="$TERM"

# ==PACKAGE MANAGER==

# check if brew or macports is installed, then total there packages and set packagehandler
if [ -e /usr/local/bin/brew ]
then
	brewpackages=$(brew list -l | tail -n +2 | wc -l | tr -d ' ')
	packageHandlerNumber=$brewpackages
	packageHandlerName="Homebrew"
elif [ -f /opt/local/bin/port ] #don't think this is the right directory, need to check later.
then
	macportpackages="`port installed | wc -l | awk '{print $1 }'`"
	packageHandlerNumber=$macportpackages
	packageHandlerName="Mac Ports"
else
    packagehandler=0
fi

# ==CPU==
cpu=$(sysctl -n machdep.cpu.brand_string)
# removes (R) and (TM) from the CPU name so it fits in a standard 80 window
cpu=$(echo "$cpu" | awk '$1=$1' | sed 's/([A-Z]\{1,2\})//g')

# ==MEMORY==
hwmemsize=$(sysctl -n hw.memsize)
hwmemsize="$((hwmemsize / 2**30)) GB"

# ==DISK==
disk=`df -Hl | head -2 | tail -1`
dpercent=`echo $disk | awk '{print $5}'`
dfree=`echo $disk | awk '{print $4}'`
dused=`echo $disk | awk '{print $3}'`
dcapacity=`echo $disk | awk '{print $2}'`


userText="${textColor}User:${normal}"
hostnameText="${textColor}Hostname:${normal}"
modelText="${textColor}Model:${normal}"
versionText="${textColor}Version:${normal}"
uptimeText="${textColor}Uptime:${normal}"
shellText="${textColor}Shell:${normal}"
terminalText="${textColor}Terminal:${normal}"
packagehandlerText="${textColor}Packages:${normal}"
cpuText="${BL}${textColor}CPU:${normal}"
memoryText="${textColor}Memory:${normal}"
graphicsText="${textColor}Graphics:${normal}"
resolutionText="${textColor}Resolution:${normal}"
diskText="${textColor}Disk:${normal}"
ipText="${textColor}IP:${normal}"

echo -e "

${GR}                     ,            $userText $user
${GR}                  ,##;            $hostnameText $hostname
${GR}                 ####             $modelText $modelname
${GR}                ;#'               $versionText $version
${GR}       ,#####;,   ,;#####;,       $uptimeText $uptime
${GR}     ######################'      $shellText $shell
${YE}    #####################'        $terminalText $terminal
${YE}    #####################         $packagehandlerText $packageHandlerNumber ($packageHandlerName)
${LR}    #####################         $cpuText $cpu
${RE}    ######################,       $memoryText $hwmemsize
${RE}     #######################      $graphicsText $graphicsnoBrand
${PU}      ####################'       $resolutionText $resolution
${BL}        #################'        $diskText $dused / $dcapacity, $dpercent
${BL}         '####''''####'           $ipText $ip_address
                                       ${normal}
"
