#!/bin/bash
DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

# Colors Variables
red="1"
green="2"
yellow="3"
blue="4"
purple="5"
lightblue="6"
grey="7"

textColor=$(tput setaf $lightblue)
normal=$(tput sgr0)

# While loops for script arguments
while [ $# -gt 0 ]
do
	case "$1" in

    -c|--color)
			GR='\033[38;5;70m'
			YE='\033[38;5;220m'
			OR='\033[38;5;172m'
			RE='\033[38;5;160m'
			PU='\033[38;5;89m'
			BL='\033[38;5;32m'
    	    shift
            ;;
	-red)
			textColor=$(tput setaf $red)
			shift
			;;
	-green)
			textColor=$(tput setaf $green)
			shift
			;;
	-yellow)
			textColor=$(tput setaf $yellow)
			shift
			;;
	-blue)
			textColor=$(tput setaf $blue)
			shift
			;;
	-purple)
			textColor=$(tput setaf $purple)
			shift
			;;
	-grey)
			textColor=$(tput setaf $grey)
			shift
			;;
	*)
			break
			;;
	esac
done

# ==USER==
user=$(whoami)

# ==HOSTNAME==
hostname=$(HOSTNAME | sed 's/.local//g' | sed 's/.gateway//g' )
# if hostname is >35 characters, truncates to make it fit on std. 80 window
if [ ${#HOSTNAME} -gt 35 ]
then
   hostname=${HOSTNAME:0:35}
fi

# ==MODEL==
serial_number=$(ioreg -c IOPlatformExpertDevice -d 2 | awk -F\" '/IOPlatformSerialNumber/{print $(NF-1)}')

if [[ $serial_number =~ ^VM ]]; then
	modelname="Virtual Machine"
else
	modelname=$( curl -s http://support-sp.apple.com/sp/product?cc=$( ioreg -c IOPlatformExpertDevice -d 2 | awk -F\" '/IOPlatformSerialNumber/{ sn=$(NF-1); if (length(sn) == 12) count=3; else if (length(sn) == 11) count=2; print substr(sn, length(sn) - count, length(sn))}' ) | xmllint --xpath '//configCode/text()' - )
fi

model=$(sysctl -n hw.model)
modelname="$modelname ($model)"

# ==GRAPHICS==
# Small optimization to make the script a touch faster via ev0rtex
# https://github.com/ev0rtex/macInfo/blob/abd4c19741098d5ae6f2f451cc96bbf49784c168/macInfo
graphicsData=$(system_profiler SPDisplaysDataType)
graphics=$(awk -F': ' '/Model/{print $NF}' <<< "$graphicsData" | paste -sd "/" -)
graphics_memory=$(awk -F': ' '/VRAM/{print $NF}' <<< "$graphicsData")
graphics="$graphics $graphics_memory"

# ==IP ADDRESS==
# Find an active network interface
interface=$(route get 0.0.0.0 2>/dev/null | awk '/interface: / {print $2}')

# Obtain the computer's IP address.
ip_address=$(ipconfig getifaddr ${interface})


# ==VERSION==
product_version=$(sw_vers -productVersion)
product_build=$(sw_vers -buildVersion)

os_marketing_name=$(curl -s "http://support-sp.apple.com/sp/product?edid=$(sw_vers -productVersion)&lang=en-US_US" |\
	xmllint --xpath '//configCode/text()' -)

version="$os_marketing_name $product_version ($product_build)"

# ==UPTIME==
boottime=$(sysctl -n kern.boottime | awk '{print $4}' | sed 's/,//')
currenttime=$(date +%s)
uptime=$(expr $currenttime - $boottime)
uptime=$(printf '%d days %dh:%dm:%ds\n' $(($uptime/86400)) $(($uptime%86400/3600)) $(($uptime%3600/60)) $(($uptime%60)))

# ==SHELL==
shell="$SHELL"

# ==CPU==
cpu=$(sysctl -n machdep.cpu.brand_string)
# removes (R) and (TM) from the CPU name so it fits in a standard 80 window
cpu=$(echo "$cpu" | awk '$1=$1' | sed 's/([A-Z]\{1,2\})//g')

# ==MEMORY==
hwmemsize=$(sysctl -n hw.memsize)
hwmemsize="$((hwmemsize / 2**30)) GB"

# ==DISK==
disk=`df -Hl | head -2 | tail -1`
dpercent=`echo $disk | awk '{print $5}'`
dfree=`echo $disk | awk '{print $4}'`
dused=`echo $disk | awk '{print $3}'`
dcapacity=`echo $disk | awk '{print $2}'`


userText="${textColor}User:${normal}"
hostnameText="${textColor}Hostname:${normal}"
modelText="${textColor}Model:${normal}"
versionText="${textColor}Version:${normal}"
uptimeText="${textColor}Uptime:${normal}"
shellText="${textColor}Shell:${normal}"
terminalText="${textColor}Terminal:${normal}"
cpuText="${BL}${textColor}CPU:${normal}"
memoryText="${textColor}Memory:${normal}"
graphicsText="${textColor}Graphics:${normal}"
resolutionText="${textColor}Resolution:${normal}"
diskText="${textColor}Disk:${normal}"
ipText="${textColor}IP:${normal}"

echo -e "

${GR}                     ,            $userText $user
${GR}                  ,##;            $hostnameText $hostname
${GR}                 ####             $modelText $modelname
${GR}                ;#'               $versionText $version
${GR}       ,#####;,   ,;#####;,       $uptimeText $uptime
${GR}     ,#####################'      $shellText $shell
${YE}    ,####################'        $terminalText $terminal
${YE}    ####################'         $cpuText $cpu
${OR}    ####################          $memoryText $hwmemsize
${OR}    #####################         
${RE}    '#####################,       
${RE}     #######################      
${PU}      #####################'      
${PU}       ###################'       $diskText $dused / $dcapacity, $dpercent
${BL}        #################'        $ipText $ip_address
${BL}         '####''''####'           ${normal}
                                       
"
